In [108]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [109]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [110]:
movies = pd.read_csv(r"C:\Users\Parth\Downloads\Movie+Assignment+Data.csv") # Write your code for importing the csv file here
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [111]:
# Write your code for inspection here
movies.shape

(5043, 28)

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [112]:
# Write your code for column-wise null count here
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [113]:
# Write your code for row-wise null count here
movies.isnull().sum(axis = 1)

0        0
1        0
2        0
3        0
4       14
        ..
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [114]:
# Write your code for column-wise null percentages here
round(movies.isnull().sum(axis = 1)/ len(movies.index)*100, 2)

0       0.00
1       0.00
2       0.00
3       0.00
4       0.28
        ...
5038    0.08
5039    0.10
5040    0.08
5041    0.04
5042    0.00
Length: 5043, dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [115]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
movies.drop(columns = [
    'director_facebook_likes',
    'actor_1_facebook_likes',
    'actor_2_facebook_likes',
    'actor_3_facebook_likes',
    'actor_2_name',
    'cast_total_facebook_likes',
    'actor_3_name',
    'duration',
    'facenumber_in_poster',
    'content_rating',
    'country',
    'movie_imdb_link',
    'aspect_ratio',
    'plot_keywords'
], inplace = True)
movies.shape

(5043, 14)

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [116]:
# Write your code for dropping the rows here
round(movies.isnull().sum(axis = 0)/ len(movies.index)*100, 2) > 5

color                     False
director_name             False
num_critic_for_reviews    False
gross                      True
genres                    False
actor_1_name              False
movie_title               False
num_voted_users           False
num_user_for_reviews      False
language                  False
budget                     True
title_year                False
imdb_score                False
movie_facebook_likes      False
dtype: bool

In [117]:
movies = movies[~pd.isnull(movies.gross)]
movies = movies[~pd.isnull(movies.budget)]
movies.shape

(3891, 14)

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [118]:
# Write your code for dropping the rows here
movies = movies[movies.isnull().sum(axis = 1) <= 5]
movies.shape

(3891, 14)

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [119]:
# Write your code for filling the NaN values in the 'language' column here
movies.language.describe()

count        3887
unique         37
top       English
freq         3707
Name: language, dtype: object

In [120]:
movies['language'] = movies.language.fillna('English')
movies.isnull().sum(axis = 0)

color                     2
director_name             0
num_critic_for_reviews    1
gross                     0
genres                    0
actor_1_name              3
movie_title               0
num_voted_users           0
num_user_for_reviews      0
language                  0
budget                    0
title_year                0
imdb_score                0
movie_facebook_likes      0
dtype: int64

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [121]:
# Write your code for checking number of retained rows here
movies.shape[0]/5042

0.771717572391908

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [122]:
# Write your code for unit conversion here
movies['gross'] = movies['gross']/1000000
movies['budget'] = movies['budget']/1000000
movies.head()

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,Color,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000
1,Color,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0,2007.0,7.1,0
2,Color,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0,2015.0,6.8,85000
3,Color,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0,2012.0,8.5,164000
5,Color,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7,2012.0,6.6,24000

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [123]:
# Write your code for creating the profit column here
movies['profit'] = movies['gross'] - movies['budget'] 
movies.head()

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,Color,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
1,Color,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0,2007.0,7.1,0,9.404152
2,Color,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0,2015.0,6.8,85000,-44.925825
3,Color,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0,2012.0,8.5,164000,198.130642
5,Color,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7,2012.0,6.6,24000,-190.641321

In [124]:
# Write your code for sorting the dataframe here
movies = movies.sort_values(by = 'profit', ascending = False)
movies.head()

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,Color,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Color,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,Color,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,Color,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Color,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459

In [125]:
top10 = movies.iloc[:10, ]
top10

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,Color,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Color,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,Color,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,Color,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Color,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Color,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
17,Color,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Color,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,Color,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Color,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [126]:
# Write your code for dropping duplicate values here
movies = movies.drop_duplicates()
movies

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,Color,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.000000,2009.0,7.9,33000,523.505847
29,Color,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.000000,2015.0,7.0,150000,502.177271
26,Color,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.000000,1997.0,7.7,26000,458.672302
3024,Color,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.000000,1977.0,8.7,33000,449.935665
3080,Color,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.500000,1982.0,7.9,34000,424.449459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Color,Katsuhiro Ôtomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2127.519898,2004.0,6.9,973,-2127.109510
2323,Color,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809
3005,Color,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112
3859,Color,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.000000,2005.0,7.7,4000,-4199.788333
2988,Color,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.500000,2006.0,7.0,7000,-12213.298588

In [127]:
# Write code for repeating subtask 2 here
top10 = movies.iloc[:10, ]
top10

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,Color,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Color,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,Color,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,Color,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Color,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Color,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Color,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,Color,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Color,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061
439,Color,Gary Ross,673.0,407.999255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.0,2012.0,7.3,140000,329.999255

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [128]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
IMDB_TOP_250 = movies.sort_values(by = 'imdb_score', ascending = False)
IMDB_TOP_250 = IMDB_TOP_250[IMDB_TOP_250.num_voted_users > 25000].iloc[:250, ]
IMDB_TOP_250['Rank'] = range(1, 251)
IMDB_TOP_250

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
1937,Color,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.0,1994.0,9.3,108000,3.341469,1
3466,Color,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.0,1972.0,9.2,43000,128.821952,2
66,Color,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061,3
2837,Color,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.0,1974.0,9.0,14000,44.300000,4
339,Color,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.0,2003.0,8.9,16000,283.019252,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,Color,Cameron Crowe,149.0,32.522352,Adventure|Comedy|Drama|Music,Philip Seymour Hoffman,Almost Famous,207287,822.0,English,60.0,2000.0,7.9,15000,-27.477648,246
99,Color,Peter Jackson,645.0,303.001229,Adventure|Fantasy,Aidan Turner,The Hobbit: An Unexpected Journey,637246,1367.0,English,180.0,2012.0,7.9,166000,123.001229,247
1606,Color,Nick Cassavetes,177.0,0.064286,Drama|Romance,Ryan Gosling,The Notebook,396396,1111.0,English,29.0,2004.0,7.9,57000,-28.935714,248
1735,Color,James Mangold,291.0,119.518352,Biography|Drama|Music|Romance,Sandra Ellis Lafferty,Walk the Line,188637,815.0,English,28.0,2005.0,7.9,11000,91.518352,249
639,Color,Michael Mann,209.0,28.965197,Biography|Drama|Thriller,Al Pacino,The Insider,133526,521.0,English,68.0,1999.0,7.9,0,-39.034803,250

In [129]:
# Write your code to extract top foreign language films from 'IMDb_Top_250' here
Top_Foreign_Lang_Film = IMDB_TOP_250[IMDB_TOP_250.language != 'English']
Top_Foreign_Lang_Film

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
4498,Color,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000,1966.0,8.9,20000,4.900000,7
4029,Color,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.300000,2002.0,8.7,28000,4.263397,17
4747,Black and White,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.000000,1954.0,8.7,11000,-1.730939,19
2373,Color,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.000000,2001.0,8.6,28000,-8.950114,22
4259,Color,Florian Henckel von Donnersmarck,215.0,11.284657,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.000000,2006.0,8.5,39000,9.284657,29
4921,Color,Majid Majidi,46.0,0.925402,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,0.180000,1997.0,8.5,0,0.745402,32
4105,Color,Chan-wook Park,305.0,2.181290,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.000000,2003.0,8.4,43000,-0.818710,48
1298,Black and White,Jean-Pierre Jeunet,242.0,33.201661,Comedy|Romance,Mathieu Kassovitz,Amélie,534262,1314.0,French,77.000000,2001.0,8.4,39000,-43.798339,54
1329,Color,S.S. Rajamouli,44.0,6.498000,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,18.026148,2015.0,8.4,21000,-11.528148,57
2323,Color,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809,58
2970,Color,Wolfgang Petersen,96.0,11.433134,Adventure|Drama|Thriller|War,Jürgen Prochnow,Das Boot,168203,426.0,German,14.000000,1981.0,8.4,11000,-2.566866,59
4659,Color,Asghar Farhadi,354.0,7.098492,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,0.500000,2011.0,8.4,48000,6.598492,60
4033,Color,Thomas Vinterberg,349.0,0.610968,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.800000,2012.0,8.3,60000,-3.189032,63
2829,Color,Oliver Hirschbiegel,192.0,5.501940,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,13.500000,2004.0,8.3,14000,-7.998060,78
2734,Black and White,Fritz Lang,260.0,0.026435,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.000000,1927.0,8.3,12000,-5.973565,84
3550,Color,Denis Villeneuve,226.0,6.857096,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.800000,2010.0,8.2,37000,0.057096,91
4000,Color,Juan José Campanella,262.0,20.167424,Drama|Mystery|Thriller,Ricardo Darín,The Secret in Their Eyes,131831,231.0,Spanish,2.000000,2009.0,8.2,33000,18.167424,92
2047,Color,Hayao Miyazaki,212.0,4.710455,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,24.000000,2004.0,8.2,13000,-19.289545,94
2551,Color,Guillermo del Toro,406.0,37.623143,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,13.500000,2006.0,8.2,27000,24.123143,102
3553,Color,José Padilha,142.0,0.008060,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.000000,2007.0,8.1,11000,-3.991940,108
2914,Color,Je-kyu Kang,86.0,1.110186,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,12.800000,2004.0,8.1,0,-11.689814,121
2830,Color,Alejandro Amenábar,157.0,2.086345,Biography|Drama|Romance,Belén Rueda,The Sea Inside,64556,140.0,Spanish,10.000000,2004.0,8.1,0,-7.913655,124
4267,Color,Alejandro G. Iñárritu,157.0,5.383834,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.000000,2000.0,8.1,11000,3.383834,132
3423,Color,Katsuhiro Ôtomo,150.0,0.439162,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.000000,1988.0,8.1,0,-1099.560838,138
4461,Color,Thomas Vinterberg,98.0,1.647780,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.300000,1998.0,8.1,5000,0.347780,139
3344,Color,Karan Johar,210.0,4.018695,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,12.000000,2010.0,8.0,27000,-7.981305,157
4284,Color,Ari Folman,231.0,2.283276,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.500000,2008.0,8.0,0,0.783276,183
3456,Color,Vincent Paronnaud,242.0,4.443403,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.300000,2007.0,8.0,14000,-2.856597,184
4144,Color,Walter Salles,71.0,5.595428,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.900000,1998.0,8.0,0,2.695428,193
4897,Color,Sergio Leone,122.0,3.500000,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,0.200000,1964.0,8.0,0,3.300000,200
3677,Color,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.500000,2004.0,7.9,0,-1.870242,206
4640,Color,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.590000,2007.0,7.9,14000,0.595783,208
4415,Color,Fabián Bielinsky,94.0,1.221261,Crime|Drama|Thriller,Ricardo Darín,Nine Queens,38215,125.0,Spanish,1.500000,2000.0,7.9,0,-0.278739,215
2863,Color,Clint Eastwood,251.0,13.753931,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,19.000000,2006.0,7.9,5000,-5.246069,221
3510,Color,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.000000,2004.0,7.9,2000,-4.078262,228
3264,Color,Michael Haneke,447.0,0.225377,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.900000,2012.0,7.9,33000,-8.674623,230

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [130]:
# Write your code for extracting the top 10 directors here
directors = movies.pivot_table(index = 'director_name', values = 'imdb_score', aggfunc = 'mean')
directors = directors.sort_values(by = 'imdb_score', ascending = False)
top10director = directors.iloc[:10, ]
top10director

                       imdb_score
director_name
Charles Chaplin          8.600000
Tony Kaye                8.600000
Alfred Hitchcock         8.500000
Ron Fricke               8.500000
Damien Chazelle          8.500000
Majid Majidi             8.500000
Sergio Leone             8.433333
Christopher Nolan        8.425000
S.S. Rajamouli           8.400000
Marius A. Markevicius    8.400000

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [131]:
# Write your code for extracting the first two genres of each movie here
movies['genres'] = movies['genres'].str.split('|')
movies['genre_1'] = movies.genres.apply(lambda x: x[0])
movies['genre_2'] = movies.genres.apply(lambda x: x[1] if len(x) > 1 else x[0])
movies

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
0,Color,James Cameron,723.0,760.505847,"[Action, Adventure, Fantasy, Sci-Fi]",CCH Pounder,Avatar,886204,3054.0,English,237.000000,2009.0,7.9,33000,523.505847,Action,Adventure
29,Color,Colin Trevorrow,644.0,652.177271,"[Action, Adventure, Sci-Fi, Thriller]",Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.000000,2015.0,7.0,150000,502.177271,Action,Adventure
26,Color,James Cameron,315.0,658.672302,"[Drama, Romance]",Leonardo DiCaprio,Titanic,793059,2528.0,English,200.000000,1997.0,7.7,26000,458.672302,Drama,Romance
3024,Color,George Lucas,282.0,460.935665,"[Action, Adventure, Fantasy, Sci-Fi]",Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.000000,1977.0,8.7,33000,449.935665,Action,Adventure
3080,Color,Steven Spielberg,215.0,434.949459,"[Family, Sci-Fi]",Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.500000,1982.0,7.9,34000,424.449459,Family,Sci-Fi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Color,Katsuhiro Ôtomo,105.0,0.410388,"[Action, Adventure, Animation, Family, Sci-Fi,...",William Hootkins,Steamboy,13727,79.0,Japanese,2127.519898,2004.0,6.9,973,-2127.109510,Action,Adventure
2323,Color,Hayao Miyazaki,174.0,2.298191,"[Adventure, Animation, Fantasy]",Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809,Adventure,Animation
3005,Color,Lajos Koltai,73.0,0.195888,"[Drama, Romance, War]",Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112,Drama,Romance
3859,Color,Chan-wook Park,202.0,0.211667,"[Crime, Drama]",Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.000000,2005.0,7.7,4000,-4199.788333,Crime,Drama
2988,Color,Joon-ho Bong,363.0,2.201412,"[Comedy, Drama, Horror, Sci-Fi]",Doona Bae,The Host,68883,279.0,Korean,12215.500000,2006.0,7.0,7000,-12213.298588,Comedy,Drama

In [132]:
# Write your code for grouping the dataframe here
movies_by_segment = movies.groupby(['genre_1', 'genre_2'])

In [133]:
# Write your code for getting the 5 most popular combo of genres here
PopGenre = pd.DataFrame(movies_by_segment['gross'].mean()).sort_values(by = 'gross', ascending = False)
PopGenre.iloc[:5, ]

                          gross
genre_1   genre_2
Family    Sci-Fi     434.949459
Adventure Sci-Fi     228.627758
          Family     118.919540
          Animation  116.998550
Action    Adventure  109.595465

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [134]:
# Write your code for creating three new dataframes here
# Include all movies in which Meryl_Streep is the lead
Meryl_Streep = movies[movies.actor_1_name == 'Meryl Streep']
Meryl_Streep

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1408,Color,David Frankel,208.0,124.732962,"[Comedy, Drama, Romance]",Meryl Streep,The Devil Wears Prada,286178,631.0,English,35.0,2006.0,6.8,0,89.732962,Comedy,Drama
1575,Color,Sydney Pollack,66.0,87.100000,"[Biography, Drama, Romance]",Meryl Streep,Out of Africa,52339,200.0,English,31.0,1985.0,7.2,0,56.100000,Biography,Drama
1204,Color,Nora Ephron,252.0,94.125426,"[Biography, Drama, Romance]",Meryl Streep,Julie & Julia,79264,277.0,English,40.0,2009.0,7.0,13000,54.125426,Biography,Drama
1618,Color,David Frankel,234.0,63.536011,"[Comedy, Drama, Romance]",Meryl Streep,Hope Springs,34258,178.0,English,30.0,2012.0,6.3,0,33.536011,Comedy,Drama
410,Color,Nancy Meyers,187.0,112.703470,"[Comedy, Drama, Romance]",Meryl Streep,It's Complicated,69860,214.0,English,85.0,2009.0,6.6,0,27.703470,Comedy,Drama
2781,Color,Phyllida Lloyd,331.0,29.959436,"[Biography, Drama, History]",Meryl Streep,The Iron Lady,82327,350.0,English,13.0,2011.0,6.4,18000,16.959436,Biography,Drama
1925,Color,Stephen Daldry,174.0,41.597830,"[Drama, Romance]",Meryl Streep,The Hours,102123,660.0,English,25.0,2002.0,7.6,0,16.597830,Drama,Romance
3135,Color,Robert Altman,211.0,20.338609,"[Comedy, Drama, Music]",Meryl Streep,A Prairie Home Companion,19655,280.0,English,10.0,2006.0,6.8,683,10.338609,Comedy,Drama
1106,Color,Curtis Hanson,42.0,46.815748,"[Action, Adventure, Crime, Thriller]",Meryl Streep,The River Wild,32544,69.0,English,45.0,1994.0,6.3,0,1.815748,Action,Adventure
1674,Color,Carl Franklin,64.0,23.209440,[Drama],Meryl Streep,One True Thing,9283,112.0,English,30.0,1998.0,7.0,592,-6.790560,Drama,Drama
1483,Color,Robert Redford,227.0,14.998070,"[Drama, Thriller, War]",Meryl Streep,Lions for Lambs,41170,298.0,English,35.0,2007.0,6.2,0,-20.001930,Drama,Thriller

In [135]:
Leo_Caprio = movies[movies.actor_1_name == 'Leonardo DiCaprio'] 
Leo_Caprio
# Include all movies in which Leo_Caprio is the lead

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
26,Color,James Cameron,315.0,658.672302,"[Drama, Romance]",Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302,Drama,Romance
97,Color,Christopher Nolan,642.0,292.568851,"[Action, Adventure, Sci-Fi, Thriller]",Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.568851,Action,Adventure
911,Color,Steven Spielberg,194.0,164.435221,"[Biography, Crime, Drama]",Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52.0,2002.0,8.0,15000,112.435221,Biography,Crime
296,Color,Quentin Tarantino,765.0,162.804648,"[Drama, Western]",Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.0,2012.0,8.5,199000,62.804648,Drama,Western
179,Color,Alejandro G. Iñárritu,556.0,183.635922,"[Adventure, Drama, Thriller, Western]",Leonardo DiCaprio,The Revenant,406020,1188.0,English,135.0,2015.0,8.1,190000,48.635922,Adventure,Drama
452,Color,Martin Scorsese,490.0,127.968405,"[Mystery, Thriller]",Leonardo DiCaprio,Shutter Island,786092,964.0,English,80.0,2010.0,8.1,53000,47.968405,Mystery,Thriller
361,Color,Martin Scorsese,352.0,132.373442,"[Crime, Drama, Thriller]",Leonardo DiCaprio,The Departed,873649,2054.0,English,90.0,2006.0,8.5,29000,42.373442,Crime,Drama
50,Color,Baz Luhrmann,490.0,144.812796,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
3476,Color,Baz Luhrmann,490.0,144.812796,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
2757,Color,Baz Luhrmann,106.0,46.338728,"[Drama, Romance]",Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14.5,1996.0,6.8,10000,31.838728,Drama,Romance
1422,Color,Randall Wallace,83.0,56.876365,"[Action, Adventure]",Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35.0,1998.0,6.4,0,21.876365,Action,Adventure
308,Color,Martin Scorsese,606.0,116.866727,"[Biography, Comedy, Crime, Drama]",Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100.0,2013.0,8.2,138000,16.866727,Biography,Comedy
1453,Color,Clint Eastwood,392.0,37.304950,"[Biography, Crime, Drama]",Leonardo DiCaprio,J. Edgar,102728,279.0,English,35.0,2011.0,6.6,16000,2.304950,Biography,Crime
257,Black and White,Martin Scorsese,267.0,102.608827,"[Biography, Drama]",Leonardo DiCaprio,The Aviator,264318,799.0,English,110.0,2004.0,7.5,0,-7.391173,Biography,Drama
2067,Color,Jerry Zaks,45.0,12.782508,[Drama],Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23.0,1996.0,6.7,1000,-10.217492,Drama,Drama
990,Color,Danny Boyle,118.0,39.778599,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,The Beach,176169,548.0,English,50.0,2000.0,6.6,0,-10.221401,Adventure,Drama
1114,Color,Sam Mendes,323.0,22.877808,"[Drama, Romance]",Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35.0,2008.0,7.3,0,-12.122192,Drama,Romance
1560,Black and White,Sam Raimi,63.0,18.636537,"[Action, Thriller, Western]",Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32.0,1995.0,6.4,0,-13.363463,Action,Thriller
326,Color,Martin Scorsese,233.0,77.679638,"[Crime, Drama]",Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100.0,2002.0,7.5,0,-22.320362,Crime,Drama
641,Color,Ridley Scott,238.0,39.380442,"[Action, Drama, Thriller]",Leonardo DiCaprio,Body of Lies,174248,263.0,English,70.0,2008.0,7.1,0,-30.619558,Action,Drama
307,Color,Edward Zwick,166.0,57.366262,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100.0,2006.0,8.0,14000,-42.633738,Adventure,Drama

In [136]:
Brad_Pitt = movies[movies.actor_1_name == 'Brad Pitt'] 
Brad_Pitt
# Include all movies in which Brad_Pitt is the lead

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
400,Color,Steven Soderbergh,186.0,183.405771,"[Crime, Thriller]",Brad Pitt,Ocean's Eleven,402645,845.0,English,85.0,2001.0,7.8,0,98.405771,Crime,Thriller
255,Color,Doug Liman,233.0,186.336103,"[Action, Comedy, Crime, Romance, Thriller]",Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120.0,2005.0,6.5,0,66.336103,Action,Comedy
940,Color,Neil Jordan,120.0,105.264608,"[Drama, Fantasy, Horror]",Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60.0,1994.0,7.6,11000,45.264608,Drama,Fantasy
470,Color,David Ayer,406.0,85.707116,"[Action, Drama, War]",Brad Pitt,Fury,303185,701.0,English,68.0,2014.0,7.6,82000,17.707116,Action,Drama
254,Color,Steven Soderbergh,198.0,125.531634,"[Crime, Thriller]",Brad Pitt,Ocean's Twelve,284852,627.0,English,110.0,2004.0,6.4,0,15.531634,Crime,Thriller
2204,Color,Alejandro G. Iñárritu,285.0,34.300771,[Drama],Brad Pitt,Babel,243799,908.0,English,25.0,2006.0,7.5,0,9.300771,Drama,Drama
2682,Color,Andrew Dominik,414.0,14.938570,"[Crime, Thriller]",Brad Pitt,Killing Them Softly,111625,369.0,English,15.0,2012.0,6.2,20000,-0.061430,Crime,Thriller
2898,Color,Tony Scott,122.0,12.281500,"[Action, Crime, Drama, Romance, Thriller]",Brad Pitt,True Romance,163492,460.0,English,13.0,1993.0,8.0,15000,-0.718500,Action,Crime
2333,Color,Angelina Jolie Pitt,131.0,0.531009,"[Drama, Romance]",Brad Pitt,By the Sea,7976,61.0,English,10.0,2015.0,5.3,0,-9.468991,Drama,Romance
1490,Color,Terrence Malick,584.0,13.303319,"[Drama, Fantasy]",Brad Pitt,The Tree of Life,136367,975.0,English,32.0,2011.0,6.7,39000,-18.696681,Drama,Fantasy
101,Color,David Fincher,362.0,127.490802,"[Drama, Fantasy, Romance]",Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150.0,2008.0,7.8,23000,-22.509198,Drama,Fantasy
683,Color,David Fincher,315.0,37.023395,[Drama],Brad Pitt,Fight Club,1347461,2968.0,English,63.0,1999.0,8.8,48000,-25.976605,Drama,Drama
1722,Color,Andrew Dominik,273.0,3.904982,"[Biography, Crime, Drama, History, Western]",Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30.0,2007.0,7.5,0,-26.095018,Biography,Crime
611,Color,Jean-Jacques Annaud,76.0,37.901509,"[Adventure, Biography, Drama, History, War]",Brad Pitt,Seven Years in Tibet,96385,119.0,English,70.0,1997.0,7.0,0,-32.098491,Adventure,Biography
792,Color,Patrick Gilmore,98.0,26.288320,"[Adventure, Animation, Comedy, Drama, Family, ...",Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60.0,2003.0,6.7,880,-33.711680,Adventure,Animation
147,Color,Wolfgang Petersen,220.0,133.228348,[Adventure],Brad Pitt,Troy,381672,1694.0,English,175.0,2004.0,7.2,0,-41.771652,Adventure,Adventure
382,Color,Tony Scott,142.0,0.026871,"[Action, Crime, Thriller]",Brad Pitt,Spy Game,121259,361.0,English,92.0,2001.0,7.0,0,-91.973129,Action,Crime

In [137]:
# Write your code for combining the three dataframes here
comb = pd.concat([Meryl_Streep, Leo_Caprio, Brad_Pitt])
comb

,color,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
1408,Color,David Frankel,208.0,124.732962,"[Comedy, Drama, Romance]",Meryl Streep,The Devil Wears Prada,286178,631.0,English,35.0,2006.0,6.8,0,89.732962,Comedy,Drama
1575,Color,Sydney Pollack,66.0,87.100000,"[Biography, Drama, Romance]",Meryl Streep,Out of Africa,52339,200.0,English,31.0,1985.0,7.2,0,56.100000,Biography,Drama
1204,Color,Nora Ephron,252.0,94.125426,"[Biography, Drama, Romance]",Meryl Streep,Julie & Julia,79264,277.0,English,40.0,2009.0,7.0,13000,54.125426,Biography,Drama
1618,Color,David Frankel,234.0,63.536011,"[Comedy, Drama, Romance]",Meryl Streep,Hope Springs,34258,178.0,English,30.0,2012.0,6.3,0,33.536011,Comedy,Drama
410,Color,Nancy Meyers,187.0,112.703470,"[Comedy, Drama, Romance]",Meryl Streep,It's Complicated,69860,214.0,English,85.0,2009.0,6.6,0,27.703470,Comedy,Drama
2781,Color,Phyllida Lloyd,331.0,29.959436,"[Biography, Drama, History]",Meryl Streep,The Iron Lady,82327,350.0,English,13.0,2011.0,6.4,18000,16.959436,Biography,Drama
1925,Color,Stephen Daldry,174.0,41.597830,"[Drama, Romance]",Meryl Streep,The Hours,102123,660.0,English,25.0,2002.0,7.6,0,16.597830,Drama,Romance
3135,Color,Robert Altman,211.0,20.338609,"[Comedy, Drama, Music]",Meryl Streep,A Prairie Home Companion,19655,280.0,English,10.0,2006.0,6.8,683,10.338609,Comedy,Drama
1106,Color,Curtis Hanson,42.0,46.815748,"[Action, Adventure, Crime, Thriller]",Meryl Streep,The River Wild,32544,69.0,English,45.0,1994.0,6.3,0,1.815748,Action,Adventure
1674,Color,Carl Franklin,64.0,23.209440,[Drama],Meryl Streep,One True Thing,9283,112.0,English,30.0,1998.0,7.0,592,-6.790560,Drama,Drama
1483,Color,Robert Redford,227.0,14.998070,"[Drama, Thriller, War]",Meryl Streep,Lions for Lambs,41170,298.0,English,35.0,2007.0,6.2,0,-20.001930,Drama,Thriller
26,Color,James Cameron,315.0,658.672302,"[Drama, Romance]",Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302,Drama,Romance
97,Color,Christopher Nolan,642.0,292.568851,"[Action, Adventure, Sci-Fi, Thriller]",Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.568851,Action,Adventure
911,Color,Steven Spielberg,194.0,164.435221,"[Biography, Crime, Drama]",Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52.0,2002.0,8.0,15000,112.435221,Biography,Crime
296,Color,Quentin Tarantino,765.0,162.804648,"[Drama, Western]",Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.0,2012.0,8.5,199000,62.804648,Drama,Western
179,Color,Alejandro G. Iñárritu,556.0,183.635922,"[Adventure, Drama, Thriller, Western]",Leonardo DiCaprio,The Revenant,406020,1188.0,English,135.0,2015.0,8.1,190000,48.635922,Adventure,Drama
452,Color,Martin Scorsese,490.0,127.968405,"[Mystery, Thriller]",Leonardo DiCaprio,Shutter Island,786092,964.0,English,80.0,2010.0,8.1,53000,47.968405,Mystery,Thriller
361,Color,Martin Scorsese,352.0,132.373442,"[Crime, Drama, Thriller]",Leonardo DiCaprio,The Departed,873649,2054.0,English,90.0,2006.0,8.5,29000,42.373442,Crime,Drama
50,Color,Baz Luhrmann,490.0,144.812796,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
3476,Color,Baz Luhrmann,490.0,144.812796,"[Drama, Romance]",Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
2757,Color,Baz Luhrmann,106.0,46.338728,"[Drama, Romance]",Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14.5,1996.0,6.8,10000,31.838728,Drama,Romance
1422,Color,Randall Wallace,83.0,56.876365,"[Action, Adventure]",Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35.0,1998.0,6.4,0,21.876365,Action,Adventure
308,Color,Martin Scorsese,606.0,116.866727,"[Biography, Comedy, Crime, Drama]",Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100.0,2013.0,8.2,138000,16.866727,Biography,Comedy
1453,Color,Clint Eastwood,392.0,37.304950,"[Biography, Crime, Drama]",Leonardo DiCaprio,J. Edgar,102728,279.0,English,35.0,2011.0,6.6,16000,2.304950,Biography,Crime
257,Black and White,Martin Scorsese,267.0,102.608827,"[Biography, Drama]",Leonardo DiCaprio,The Aviator,264318,799.0,English,110.0,2004.0,7.5,0,-7.391173,Biography,Drama
2067,Color,Jerry Zaks,45.0,12.782508,[Drama],Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23.0,1996.0,6.7,1000,-10.217492,Drama,Drama
990,Color,Danny Boyle,118.0,39.778599,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,The Beach,176169,548.0,English,50.0,2000.0,6.6,0,-10.221401,Adventure,Drama
1114,Color,Sam Mendes,323.0,22.877808,"[Drama, Romance]",Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35.0,2008.0,7.3,0,-12.122192,Drama,Romance
1560,Black and White,Sam Raimi,63.0,18.636537,"[Action, Thriller, Western]",Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32.0,1995.0,6.4,0,-13.363463,Action,Thriller
326,Color,Martin Scorsese,233.0,77.679638,"[Crime, Drama]",Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100.0,2002.0,7.5,0,-22.320362,Crime,Drama
641,Color,Ridley Scott,238.0,39.380442,"[Action, Drama, Thriller]",Leonardo DiCaprio,Body of Lies,174248,263.0,English,70.0,2008.0,7.1,0,-30.619558,Action,Drama
307,Color,Edward Zwick,166.0,57.366262,"[Adventure, Drama, Thriller]",Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100.0,2006.0,8.0,14000,-42.633738,Adventure,Drama
400,Color,Steven Soderbergh,186.0,183.405771,"[Crime, Thriller]",Brad Pitt,Ocean's Eleven,402645,845.0,English,85.0,2001.0,7.8,0,98.405771,Crime,Thriller
255,Color,Doug Liman,233.0,186.336103,"[Action, Comedy, Crime, Romance, Thriller]",Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120.0,2005.0,6.5,0,66.336103,Action,Comedy
940,Color,Neil Jordan,120.0,105.264608,"[Drama, Fantasy, Horror]",Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60.0,1994.0,7.6,11000,45.264608,Drama,Fantasy
470,Color,David Ayer,406.0,85.707116,"[Action, Drama, War]",Brad Pitt,Fury,303185,701.0,English,68.0,2014.0,7.6,82000,17.707116,Action,Drama
254,Color,Steven Soderbergh,198.0,125.531634,"[Crime, Thriller]",Brad Pitt,Ocean's Twelve,284852,627.0,English,110.0,2004.0,6.4,0,15.531634,Crime,Thriller
2204,Color,Alejandro G. Iñárritu,285.0,34.300771,[Drama],Brad Pitt,Babel,243799,908.0,English,25.0,2006.0,7.5,0,9.300771,Drama,Drama
2682,Color,Andrew Dominik,414.0,14.938570,"[Crime, Thriller]",Brad Pitt,Killing Them Softly,111625,369.0,English,15.0,2012.0,6.2,20000,-0.061430,Crime,Thriller
2898,Color,Tony Scott,122.0,12.281500,"[Action, Crime, Drama, Romance, Thriller]",Brad Pitt,True Romance,163492,460.0,English,13.0,1993.0,8.0,15000,-0.718500,Action,Crime
2333,Color,Angelina Jolie Pitt,131.0,0.531009,"[Drama, Romance]",Brad Pitt,By the Sea,7976,61.0,English,10.0,2015.0,5.3,0,-9.468991,Drama,Romance
1490,Color,Terrence Malick,584.0,13.303319,"[Drama, Fantasy]",Brad Pitt,The Tree of Life,136367,975.0,English,32.0,2011.0,6.7,39000,-18.696681,Drama,Fantasy
101,Color,David Fincher,362.0,127.490802,"[Drama, Fantasy, Romance]",Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150.0,2008.0,7.8,23000,-22.509198,Drama,Fantasy
683,Color,David Fincher,315.0,37.023395,[Drama],Brad Pitt,Fight Club,1347461,2968.0,English,63.0,1999.0,8.8,48000,-25.976605,Drama,Drama
1722,Color,Andrew Dominik,273.0,3.904982,"[Biography, Crime, Drama, History, Western]",Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30.0,2007.0,7.5,0,-26.095018,Biography,Crime
611,Color,Jean-Jacques Annaud,76.0,37.901509,"[Adventure, Biography, Drama, History, War]",Brad Pitt,Seven Years in Tibet,96385,119.0,English,70.0,1997.0,7.0,0,-32.098491,Adventure,Biography
792,Color,Patrick Gilmore,98.0,26.288320,"[Adventure, Animation, Comedy, Drama, Family, ...",Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60.0,2003.0,6.7,880,-33.711680,Adventure,Animation
147,Color,Wolfgang Petersen,220.0,133.228348,[Adventure],Brad Pitt,Troy,381672,1694.0,English,175.0,2004.0,7.2,0,-41.771652,Adventure,Adventure
382,Color,Tony Scott,142.0,0.026871,"[Action, Crime, Thriller]",Brad Pitt,Spy Game,121259,361.0,English,92.0,2001.0,7.0,0,-91.973129,Action,Crime

In [138]:
# Write your code for grouping the combined dataframe here
combined = comb.groupby('actor_1_name')

In [140]:
# Write the code for finding the mean of critic reviews and audience reviews here
print(combined.num_critic_for_reviews.mean())
print(combined.num_user_for_reviews.mean())

actor_1_name
Brad Pitt            245.000000
Leonardo DiCaprio    330.190476
Meryl Streep         181.454545
Name: num_critic_for_reviews, dtype: float64
actor_1_name
Brad Pitt            742.352941
Leonardo DiCaprio    914.476190
Meryl Streep         297.181818
Name: num_user_for_reviews, dtype: float64

**Checkpoint 6:** `Leonardo` has aced both the lists!